name: Build sandbox package

on:
   push:
     branches:
       - dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup NodeJs environment
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install dependencies
      run: yarn

    - name: Build deployment package
      run: PUBLIC_URL=/assets yarn build
      env:
        CI: true
    - name: Upload the build
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws s3 sync build/ s3://frontend-build-artifacts/sandbox-react/ \
        --region eu-west-1
