name: Lint and Test Rumpel React

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup NodeJs environment
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: yarn
      - name: Test
        run: yarn test
      - name: Lint
        run: yarn lint
      - name: Build deployment package
        run: PUBLIC_URL=/assets yarn build
