name: Lint and Test Rumpel React

on: [push]
#  pull_request:
#    branches:
#      - master
#      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup NodeJs environment
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: yarn
      - name: Test
        run: yarn run test
      - name: Lint
        run: yarn run lint
      - name: Build deployment package
        run: PUBLIC_URL=/assets yarn build
